### ISSUE TITLE
Timeout and retry settings?

### ISSUE THREAD

**Issue by gaborauth** [emqx/emqx-auth-http#101]
Hi,

There is any (planned) option to set timeout and retry for HTTP authentication?

Bye,
Gábor Auth

**Comment by turtleDeng** [comment]
Thank you for your suggestion, we will implement it in version 3.2.

**Comment by gaborauth** [comment]
Thank you! What is the planned release date of the 3.2?

**Comment by turtleDeng** [comment]
Already supported in 3.2.7.
