### ISSUE TITLE
ACL request payload access field always equal to 2

### ISSUE THREAD

**Issue by enix223** [emqx/emqx-auth-http#134]
I am testing emqx with auth http plugin enabled, but my http server always receiving payload with access equal to __2__, no matter my client is trying to subscribing a topic or publishing a topic.

ACL config `emqx_auth_http.conf` goes here:

```
##--------------------------------------------------------------------
## ACL request.
##
## Variables:
##  - %A: 1 | 2, 1 = sub, 2 = pub
##  - %u: username
##  - %c: clientid
##  - %a: ipaddress
##  - %t: topic
##
## Value: URL
auth.http.acl_req = http://backend:9000/v1/auth/acl
## Value: post | get | put
auth.http.acl_req.method = post
## Value: Params
auth.http.acl_req.params = access=%A,username=%u,clientid=%c,ipaddr=%a,topic=%t
```

**Comment by HJianBo** [comment]
Sorry @enix223  It is a bug actually, and it has fixed at https://github.com/emqx/emqx/commit/f14a56eb1741006f07a86ee518de4e29c8dd5af9

Please upgrade EMQ X above v3.1.0

**Comment by enix223** [comment]
Thanks for your promptly reply. Tested with v3.2-beta.1, issue have been fixed.
