### ISSUE TITLE
auth parameters can use json format data?

### ISSUE THREAD

**Issue by kingjie0210** [emqx/emqx-auth-http#142]
now the auth parameters use "&" to Differentiate between different fields ,eg：clientid=123&username=jiangch1&password=jiangch3
but if the passwd field or clientid field contains character “&”，how to Differentiate between different fields?
In my view, auth parameters use json format data is a better way.but I do not know how to get the value of field clientid  from parameters.Can the  emqx-auth-http use json format data?

**Comment by GopherJ** [comment]
if you use sensible symbols, it will be encoded and decoded again I think

**Comment by HJianBo** [comment]
Don't worry about that. In the current implement, the '&', '=' or other special character can't cause side effect to http parameters.

But, the JSON format could a feature in the future version.

**Comment by GopherJ** [comment]
@HJianBo json format is a better option, currently it sends `undefined` to the server which is not wanted.

but json can avoid this because json format has only `null`, so that all languages can deserialize the data correctly

**Comment by GopherJ** [comment]
see also #179

**Comment by HJianBo** [comment]
it has fixed #183 

Plz try v4.1-beta.1
