### ISSUE TITLE
Add headers in auth request

### ISSUE THREAD

**Issue by steppo40** [emqx/emqx-auth-http#146]
The request forwarded by the plugin contains a minimal set of headers.

There should be a way to handle headers to work with picky webservers.
As an example here's a request captured from EMQ and one crafted to support a KeyCloak authentication system.

The EMQ request does not comply with the required *Accept* header and a 400 response code is received, while a crafted request with such header passes.

**EMQ**
```
----- Request Start ----->
/auth/realms/Ingestion/protocol/openid-connect/token
content-type: application/x-www-form-urlencoded
content-length: 117
te: 
host: localhost:8081
connection: keep-alive
client_id=emqtt_ingestion&username=2d24349a-373d-4685-a8e3-2f121e5e666d&password=CSvNsV2sPsAnC55P&grant_type=password
<----- Request End -----
```
**CRAFTED**
```
----- Request Start ----->
/auth/realms/Ingestion/protocol/openid-connect/token
Host: localhost:8081
Content-Length: 117
Accept-Encoding: gzip, deflate
Accept: */*
User-Agent: HTTPie/0.9.4
Connection: keep-alive
Content-Type: application/x-www-form-urlencoded
client_id=emqtt-ingestion&username=2d24349a-373d-4685-a8e3-2f121e5e666d&grant_type=password&password=CSvNsV2sPsAnC55P
<----- Request End -----
```

**Comment by wivwiv** [comment]
We're going to support in emqx-auth-http and emqx-web-hook.

**Comment by HJianBo** [comment]
Hi, guys The emqx_auth_http has supported it at v4.0-rc4
