### ISSUE TITLE
Is there a way to reload config from the CLI?

### ISSUE THREAD

**Issue by hoya0296** [emqx/emqx-auth-http#164]
OS : centos 7.4
emqx : 3.2.3

Is there a way to reload config from the CLI?

I know it's possible to change settings on the dashboard screen.
but i want  CLI  reload config
The emqx_ctl command does not seem to reload. 
   - "emqx_ctl plugin reload emqx_auth_http"
  -  I checked on the dashboard.
 
can not restart emqx.  (Existing sessions need to be kept connected)

**Comment by HJianBo** [comment]
Why are you want to restart emqx? 

It's enough to reload `emqx_auth_http.conf` with `emqx_ctl plugin reload emqx_auth_http`

**Comment by YiuTerran** [comment]
it should be `emqx_ctl plugins reload emqx_auth_http`
