### ISSUE TITLE
Build error: missing ssl_api.hrl

### ISSUE THREAD

**Issue by cogitaria-admin** [emqx/emqx-auth-http#197]
Have Erlang/OTP 22 installed.  Cloned the plugin and ran make:
`
> make
rebar3 compile
===> Verifying dependencies...
===> Running neotoma...
===> Compiling c_src/decoder.c
===> Compiling c_src/encoder.c
... more ...
===> Compiling emqx_reloader
===> Compiling esockd
===> Compiling _build/default/lib/esockd/src/esockd_transport.erl failed
_build/default/lib/esockd/src/esockd_transport.erl:20: can't find include lib "ssl/src/ssl_api.hrl"
`

**Comment by HJianBo** [comment]
Hi  @cogitaria-admin It is a BUG in rebar3.

Plz use the `rebar3` in the `emqx-rel` repo

**Comment by cogitaria-admin** [comment]
Thank you!
