### ISSUE TITLE
How the emqx_auth_http set value to Variable ClientInfo?

### ISSUE THREAD

**Issue by BruceOfChina** [emqx/emqx-auth-http#201]
In the file emqx-auth-http\src\emqx_auth_http_cli.erl
feedvar(Params, ClientInfo = #{clientid := ClientId,
                               protocol := Protocol,
                               peerhost := Peerhost}) ->
    lists:map(fun({Param, "%u"}) -> {Param, maps:get(username, ClientInfo, null)};
                 ({Param, "%c"}) -> {Param, ClientId};
                 ({Param, "%r"}) -> {Param, Protocol};
                 ({Param, "%a"}) -> {Param, inet:ntoa(Peerhost)};
                 ({Param, "%P"}) -> {Param, maps:get(password, ClientInfo, null)};
                 ({Param, "%p"}) -> {Param, maps:get(sockport, ClientInfo, null)};
                 ({Param, "%C"}) -> {Param, maps:get(cn, ClientInfo, null)};
                 ({Param, "%d"}) -> {Param, maps:get(dn, ClientInfo, null)};
                 ({Param, "%A"}) -> {Param, maps:get(access, ClientInfo, null)};
                 ({Param, "%t"}) -> {Param, maps:get(topic, ClientInfo, null)};
                 ({Param, "%m"}) -> {Param, maps:get(mountpoint, ClientInfo, null)};
                 ({Param, Var})  -> {Param, Var}
              end, Params)

How the variable ClientInfo get the value   cn, dn and so on ?

**Comment by HJianBo** [comment]
It just supports:
 - '%C': The common name of client's certificate
- '%d': The subject name of client's certificate

Duplicated https://github.com/emqx/emqx/issues/3726
