### ISSUE TITLE
Enable passthrough of ws_cookie in acl request

### ISSUE THREAD

**Issue by gerad** [emqx/emqx-auth-http#224]
We authenticate the user using the cookie in the web socket. I _think_ I can see how the code can be changed to allow the plugin to be configured to pass this cookie through as one of the parameters. Would that be an acceptable change to make? 

I don't have any erlang experience, and I can try to open a PR with the change – but I'm not sure I can add a test without help.

**Comment by wivwiv** [comment]
@gerad 

Sorry, websocket cookies need to be strictly discussed

1. It bypasses the authentication system of mqtt and violates the standard. The authentication information in the standard protocol should be obtained from the attributes related to mqtt

2. In fact, there are many ways on the client to insert the information in cookies into the user name, ClientID or password. In some cases, the client can read it directly mqtt.password = document.cookie You can just plug it in

3. Security issues. There is too much information in cookies, even some confidential and sensitive information. The EU cookie policy is trying to protect the bad use of cookies, and it is not recommended to transfer all cookies to another place

**Comment by wivwiv** [comment]
@gerad 
You should put the valid authentication information into MQTT username ClientID or password. Please try this method, or tell us your specific use scenario. Let's see if we can solve it.

```js
const client = mqtt.connect('ws://broker.emqx.io:8083/mqtt', {
 clientid: 'xxxx',
 username: 'xxxxxxx',
 password: document.cookie.split('; ')[0], // or (await axios.get('/mqtt-auth-token')).data.token
})
```

**Comment by zmstone** [comment]
thank you @wivwiv for the insights.
closing this issue, @gerad please feel free to reopen if necessary, or open a new one in https://github.com/emqx/emqx
