### ISSUE TITLE
Allow auth for clientid only (without username and password)

### ISSUE THREAD

**Issue by jbpin** [emqx/emqx-auth-http#64]
I would like to have an option to let's the plugin call the http service even if the username and password are empty. We still have clientId and password.

https://github.com/emqtt/emq-auth-http/blob/132a8646a7163ad2913bf158bbc795a95a8744f3/src/emq_auth_http.erl#L35-L36

Adding option like auth.http.auth_req.mandatory_username and auth.http.auth_req.mandatory_password will allow to manage this case. 

Adding anonymous access do not save this use case because I still want to validate that the client_id is registered.

**Comment by emqplus** [comment]
@jbpin Can you provide a default `username` for all the MQTT clients? Then this plugin will call the Auth API with `clientid`, `username` and `password` fields.

**Comment by jbpin** [comment]
@emqplus Thanks for the reply.
Username only is not sufficient. I have to pass a username and password in order to the call to the http service occur. After adding a default username and password (not valid as I want to validate clientid only) everything work fine. So not having to pass username and password will be a enhancement.

**Comment by jbpin** [comment]
This is from the log 

```
09:09:12.697 [error] Client(test@172.17.0.1:55476): Username 'necessary' login failed for 400
```

**Comment by emqplus** [comment]
@jbpin Check your auth API `auth.http.auth_req = http://127.0.0.1:8080/mqtt/auth`, which returned the `400` error code.

**Comment by jbpin** [comment]
Sorry that the line I mention in the initial comment when I submit with no username and no password.

```
09:21:40.497 [error] Client(test@172.17.0.1:55613): Username 'undefined' login failed for username_or_password_undefined
09:23:30.735 [error] Client(test@172.17.0.1:55617): Username 'necessary' login failed for username_or_password_undefined
```
The first call was made with no username but password, the second with username (necessary) but no password. Both connect request didn't call my http service due to the fact that no username or no password was submit. When I put the both parameters all is fine.

**Comment by sepulrator** [comment]
Any update on the issue?

**Comment by chimit** [comment]
If the emq-auth-http plugin is disabled a client is able to connect with a clientID only. But if I enable this plugin the client can't connect with empty username and password anymore. HTTP request to the auth endpoint is not even sending. And that's strange.

Why does emqtt block the connection by itself? It's all up to my auth endpoint to determine which credentials are sufficient. Just send me empty username and password.

**Comment by GerogeLeon** [comment]
the option is actually a must. i encounter a situation that a mobile-app emq client should be upgraded from anonymous auth to http auth , but some user would be still using the old version of  the mobile-app, and the old version do not hava username/password, so they can not connect to the http-auth enabled emq server

**Comment by GerogeLeon** [comment]
in my opinion, the emq server should not participate in the decision of auth result, since the auth logic is delegated to a external dedicated auth server.

**Comment by turtleDeng** [comment]
We will support it in version 3.2.

**Comment by GerogeLeon** [comment]
> We will support it in version 3.2.

when release version 3.2 ?

**Comment by HJianBo** [comment]
The stable version maybe a month later! Because we will Enhance many features of EMQ X

**Comment by GopherJ** [comment]
hello, I'm also concerned about this, when will the version 3.2 be released?

**Comment by GopherJ** [comment]
This should be imprtant for working with oauth2

**Comment by HJianBo** [comment]
We are working for 3.2.0, it could take another two weeks

**Comment by turtleDeng** [comment]
Thank you for your participation, I will close this issue.

**Comment by GopherJ** [comment]
Hello @turtleDeng can I get some documentations on this? It's closed but we don't have enough information on how should we use it.
