### ISSUE TITLE
Plugin's config can't be reloaded.  

### ISSUE THREAD

**Issue by smoomrik** [emqx/emqx-auth-http#69]
Is there possibility to reload config of plugin without restart emqttd? 

Load/Unload of the plugin is not applying new configuration file.

**Comment by terry-xiaoyu** [comment]
Hi, you could update the `app.config` directly.

The `app.config` is the config file that is converted from the `emq.conf` and the `configs of your plugins`. The app.config is then used by EMQ directly.

For example in my Mac there is a running emq, and following is the process info:

```
$ ps -ef | grep beam

501  4422  4420   0  8:41下午 ttys002    0:01.41 /Users/emqer/code/emq-relx/_rel/emqttd/erts-9.3/bin/beam.smp -W w -e 256000 -Q 65536 -P 256000 -A 32 -K true -zdbbl 8192 -- -root /Users/emqer/code/emq-relx/_rel/emqttd -progname Users/emqer/code/emq-relx/_rel/emqttd/bin/emqttd -- -home /Users/emqer -- -boot /Users/emqer/code/emq-relx/_rel/emqttd/releases/2.3.5/emqttd -mode embedded -boot_var ERTS_LIB_DIR /Users/emqer/code/emq-relx/_rel/emqttd/erts-9.3/../lib -mnesia dir "/Users/emqer/code/emq-relx/_rel/emqttd/data/mnesia/emq@127.0.0.1" -config /Users/emqer/code/emq-relx/_rel/emqttd/data/configs/app.2018.04.14.20.41.16.config -kernel net_ticktime 60 -smp auto -setcookie emqsecretcookie -proto_dist inet_tcp -name emq@127.0.0.1 -vm_args /Users/emqer/code/emq-relx/_rel/emqttd/data/configs/vm.2018.04.14.20.41.16.args -- console
```

You would notice the `-config /Users/emqer/code/emq-relx/_rel/emqttd/data/configs/app.2018.04.14.20.41.16.config` argument of the command line, which shows which config file it uses. Let's check the content of this file, jump the `emq_auth_http` section:

```
$ cat /Users/emqer/code/emq-relx/_rel/emqttd/data/configs/app.2018.04.14.20.41.16.config

...
{emq_auth_http,
     [{auth_req,
          [{url,"http://127.0.0.1:8080/mqtt/auth"},
           {method,post},
           {params,[{"clientid","%c"},{"username","%u"},{"password","%P"}]}]},
      {super_req,
          [{url,"http://127.0.0.1:8080/mqtt/superuser"},
           {method,post},
           {params,[{"clientid","%c"},{"username","%u"}]}]},
      {acl_req,
          [{url,"http://127.0.0.1:8080/mqtt/acl"},
           {method,get},
           {params,
               [{"access","%A"},
                {"username","%u"},
                {"clientid","%c"},
                {"ipaddr","%a"},
                {"topic","%t"}]}]}]}
...
```

Now you can update this section and reload your emq-auth-http plugin again. In this method it is not necessary to restart you entire emq.

Reload the configs at the runtime is still possible, but this feature is not planned in the coming versions.

**Comment by turtleDeng** [comment]
The plugin configuration has been modified in emqx-3.1-beta.1, and the reload plugin takes effect.
```
$ ./bin/emqx_ctl plugins reload emqx_auth_http
```
