### ISSUE TITLE
socket_closed_remotely

### ISSUE THREAD

**Issue by ranr** [emqx/emqx-auth-http#70]
Hi,

We are testing the plugin to authorize via a local nginx server. In our tests everything works well, except that from time to time we are getting the following error log:

HTTP http://127.0.0.1/auth Error: socket_closed_remotely
Client(***): Username '***' login failed for socket_closed_remotely

In nginx access/error logs there is no trace. It looks like the request never reached the server, so I suspect this bug emerges from the Erlang. Our machine was tuned according to the "1 million connections" guide on the website.

Any ideas?

**Comment by terry-xiaoyu** [comment]
@ranr Sorry for late reply. Do you still have that problem now? 

I would suspect that is not a issue of emq. The `socket_closed_remotely` error indicates emq was trying to send the request, but the peer closed the connection, probably because there was no process listening on port 80.

**Comment by ranr** [comment]
Hi Shawn,

Yes, I wasnt able to solve this problem. I suspected it too, but the other
process is nginx, with a straightforward configuration. The access log and
error log of nginx don't show the request at all. Looking at nginx stats
says all requests were handled. It looks like nginx never received the
request...

Any ideas how to debug this? Right now it happens every few hours with no
apparent correlation to anything.

Cheers,

**Comment by terry-xiaoyu** [comment]
Hi, could you post your logs here? Including the emq's log, and the nginx's access/error log at the time the error occurred.

**Comment by NicoMechu** [comment]
Hi, I got the same issue (although I'm using Apache).
I suspect is my fault, but can't find the problem.
The server didn't go down either.

Regards,

**Comment by terry-xiaoyu** [comment]
@NicoMechu How many users concurrently connected in your system? Did your problem occurred only when lots of connects flood in?

**Comment by NicoMechu** [comment]
@terry-xiaoyu Thanks for responding. I can't determinate a pattern for the error, but this doesn't happen only when there are lots of connects.

**Comment by ranr** [comment]
Hi Shawn,

I am running a cluster of two servers serving together tens of thousands of
clients. Previously I was using the http module for both ACL and Auth, and
I was receiving dozens of errors per second.
I ended up rewriting the ACL part, and now only use HTTP for AUTH. The
error now is pretty rare, but still occurs. I assume this is because the
amount of HTTP calls is pretty low now, only when a client connects and not
for every subscribe/publish.

Log file of last few days is below (usernames and IPs are anonymized).

Nginx error log is empty.
Nginx access log is configured to show only errors returned (so no
responses starting with 2xx), these requests don't appear there.

When I was debugging this about a month ago, I enabled full logging on
Nginx and can confirm that none of these requests ever reached nginx.

2018-04-17 02:09:21.737 [error] <0.14444.574>@emq_auth_http:check:43 HTTP
http://127.0.0.1/auth Error: socket_closed_remotely
2018-04-17 02:09:21.737 [error] <0.14444.574>@emqttd_protocol:process:234
Client(paho/4CFE2A6E7210DDEF22@62.34.23.12:37979): Username 'bigserver'
login failed for socket_closed_remotely
2018-04-17 03:40:56.028 [error] <0.23715.574>@emq_auth_http:check:43 HTTP
http://127.0.0.1/auth Error: socket_closed_remotely
2018-04-17 03:40:56.028 [error] <0.23715.574>@emqttd_protocol:process:234
Client(xYwizxk5@127.0.0.1:49598): Username 'things/xYwizxk5' login failed
for socket_closed_remotely
2018-04-17 04:51:37.099 [error] <0.26858.576>@emq_auth_http:check:43 HTTP
http://127.0.0.1/auth Error: socket_closed_remotely
2018-04-17 04:51:37.099 [error] <0.26858.576>@emqttd_protocol:process:234
Client(paho/C942F526DD2A2CC0FD@62.34.23.12:52294): Username 'bigserver'
login failed for socket_closed_remotely
2018-04-17 06:29:50.356 [error] <0.16819.575>@emq_auth_http:check:43 HTTP
http://127.0.0.1/auth Error: socket_closed_remotely
2018-04-17 06:29:50.356 [error] <0.16819.575>@emqttd_protocol:process:234
Client(paho/7C384413DD37191D17@62.34.23.12:60441): Username 'bigserver'
login failed for socket_closed_remotely
2018-04-16 04:32:07.320 [error] <0.16301.557>@emq_auth_http:check:43 HTTP
http://127.0.0.1/auth Error: socket_closed_remotely
2018-04-16 04:32:07.320 [error] <0.16301.557>@emqttd_protocol:process:234
Client(paho/D85CFE350707512687@62.34.23.12:25015): Username 'bigserver'
login failed for socket_closed_remotely
2018-04-15 03:56:14.064 [error] <0.11747.538>@emq_auth_http:check:43 HTTP
http://127.0.0.1/auth Error: socket_closed_remotely
2018-04-15 03:56:14.064 [error] <0.11747.538>@emqttd_protocol:process:234
Client(paho/2C6A29D5F4DAA37D14@62.34.23.12:37354): Username 'bigserver'
login failed for socket_closed_remotely
2018-04-15 06:48:32.154 [error] <0.21452.538>@emq_auth_http:check:43 HTTP
http://127.0.0.1/auth Error: socket_closed_remotely
2018-04-15 06:48:32.154 [error] <0.21452.538>@emqttd_protocol:process:234
Client(xr4VPsXh@127.0.0.1:35264): Username 'things/xr4VPsXh' login failed
for socket_closed_remotely
2018-04-15 13:22:38.165 [error] <0.23065.545>@emq_auth_http:check:43 HTTP
http://127.0.0.1/auth Error: socket_closed_remotely
2018-04-15 13:22:38.165 [error] <0.23065.545>@emqttd_protocol:process:234
Client(paho/D9EA9DD234703DA150@62.34.23.12:20474): Username 'bigserver'
login failed for socket_closed_remotely
2018-04-15 17:07:37.167 [error] <0.19781.548>@emq_auth_http:check:43 HTTP
http://127.0.0.1/auth Error: socket_closed_remotely
2018-04-15 17:07:37.168 [error] <0.19781.548>@emqttd_protocol:process:234
Client(xxRYYVQH@127.0.0.1:56258): Username 'things/xxRYYVQH' login failed
for socket_closed_remotely
2018-04-15 23:15:37.237 [error] <0.23890.552>@emq_auth_http:check:43 HTTP
http://127.0.0.1/auth Error: socket_closed_remotely
2018-04-15 23:15:37.237 [error] <0.23890.552>@emqttd_protocol:process:234
Client(xxriK99G@127.0.0.1:36130): Username 'things/xxriK99G' login failed
for socket_closed_remotely
2018-04-15 23:15:43.968 [error] <0.11266.553>@emq_auth_http:check:43 HTTP
http://127.0.0.1/auth Error: socket_closed_remotely
2018-04-15 23:15:43.968 [error] <0.11266.553>@emqttd_protocol:process:234
Client(xyJYYJpi@127.0.0.1:36544): Username 'things/xyJYYJpi' login failed
for socket_closed_remotely
2018-04-14 06:51:09.420 [error] <0.25923.521>@emq_auth_http:check:43 HTTP
http://127.0.0.1/auth Error: socket_closed_remotely
2018-04-14 06:51:09.420 [error] <0.25923.521>@emqttd_protocol:process:234
Client(paho/CF33175F219C5332FE@62.34.23.12:52347): Username 'bigserver'
login failed for socket_closed_remotely
2018-04-14 15:33:55.184 [error] <0.26172.528>@emq_auth_http:check:43 HTTP
http://127.0.0.1/auth Error: socket_closed_remotely
2018-04-14 15:33:55.184 [error] <0.26172.528>@emqttd_protocol:process:234
Client(paho/4411DA2A3254617C7D@62.34.23.12:19684): Username 'bigserver'
login failed for socket_closed_remotely
2018-04-13 16:41:12.763 [error] <0.21578.510>@emq_auth_http:check:43 HTTP
http://127.0.0.1/auth Error: socket_closed_remotely
2018-04-13 16:41:12.764 [error] <0.21578.510>@emqttd_protocol:process:234
Client(paho/7E117D0FDD07C49492@62.34.23.12:30468): Username 'bigserver'
login failed for socket_closed_remotely
2018-04-13 17:15:58.488 [error] <0.562.511>@emq_auth_http:check:43 HTTP
http://127.0.0.1/auth Error: socket_closed_remotely
2018-04-13 17:15:58.488 [error] <0.562.511>@emqttd_protocol:process:234
Client(paho/4D25D0578E17408EFC@62.34.23.12:34131): Username 'bigserver'
login failed for socket_closed_remotely
2018-04-12 01:26:45.666 [error] <0.8699.480>@emq_auth_http:check:43 HTTP
http://127.0.0.1/auth Error: socket_closed_remotely
2018-04-12 01:26:45.666 [error] <0.8699.480>@emqttd_protocol:process:234
Client(paho/CA2096FED33DC077DD@62.34.23.12:9879): Username 'bigserver'
login failed for socket_closed_remotely
2018-04-12 04:18:29.918 [error] <0.11326.482>@emq_auth_http:check:43 HTTP
http://127.0.0.1/auth Error: socket_closed_remotely
2018-04-12 04:18:29.918 [error] <0.11326.482>@emqttd_protocol:process:234
Client(paho/1DAD358D109F46738A@62.34.23.12:45619): Username 'bigserver'
login failed for socket_closed_remotely
2018-04-12 11:28:40.901 [error] <0.17227.487>@emq_auth_http:check:43 HTTP
http://127.0.0.1/auth Error: socket_closed_remotely
2018-04-12 11:28:40.901 [error] <0.17227.487>@emqttd_protocol:process:234
Client(paho/E46F7748DD716EFA0A@62.34.23.12:50055): Username 'bigserver'
login failed for socket_closed_remotely
2018-04-12 13:47:55.421 [error] <0.25450.489>@emq_auth_http:check:43 HTTP
http://127.0.0.1/auth Error: socket_closed_remotely
2018-04-12 13:47:55.421 [error] <0.25450.489>@emqttd_protocol:process:234
Client(xAWiVTcq@127.0.0.1:35950): Username 'things/xAWiVTcq' login failed
for socket_closed_remotely

**Comment by Leen15** [comment]
Hi to all, we have the same problem here with version 2.3.5:
![image](https://user-images.githubusercontent.com/3629071/38929188-d1291346-430b-11e8-9bd2-5674c5ce7686.png)
we have only 3 clients connected and the acl server is on the same local network.
The first client sends a timestamp on the ping channel every 5 seconds.
The strange thing: if from another client I try to publish on the same channel, it works (Hello world messages):
![image](https://user-images.githubusercontent.com/3629071/38929249-ffcf076e-430b-11e8-931d-802c35f596ad.png)
after about a minute, the first client can publish again, without touch nothing.

**Comment by terry-xiaoyu** [comment]
@Leen15 Hi, we're investigating this issue, as many guys have seen it.
Hope it get fixed in next release.

**Comment by Leen15** [comment]
Thanks @terry-xiaoyu . We would like to use emq in production but this bug stopped us because it happens every 10 minutes or less. :/
Do you have any ETA about the next release or could a hotfix / workaround be applied in the meanwhile? 
Thanks for your great work!

**Comment by terry-xiaoyu** [comment]
@Leen15 EMQ 2.3.7 would be released before next week, including the fix of this issue.
See the pull request here: https://github.com/emqtt/emq-auth-http/pull/75

**Comment by Leen15** [comment]
Great, thanks!

**Comment by thanhhm** [comment]
Happy new year,
It was pretty long but ran into httpc's problem too and had an investigation.
According to this guy [ThomasArts](https://github.com/phoenixframework/phoenix/issues/1478#issuecomment-173195841), He use another profile for difference process. After reading httpc source code I have some though:
```erl
handle_request(Request, State = #state{options = Options}) ->
    NewRequest = handle_cookies(generate_request_id(Request), State),
    SessionType = session_type(Options),
    case select_session(Request#request.method,
			Request#request.address,
			Request#request.scheme, SessionType, State) of
	{ok, HandlerPid} ->
	    pipeline_or_keep_alive(NewRequest, HandlerPid, State);
	no_connection ->
	    start_handler(NewRequest, State);
	{no_session,  OpenSessions} when OpenSessions
	< Options#options.max_sessions ->
	    start_handler(NewRequest, State);
	{no_session, _} ->
	    %% Do not start any more persistent connections
	    %% towards this server.
	    NewHeaders =
		(NewRequest#request.headers)#http_request_h{connection
							    = "close"},
	    start_handler(NewRequest#request{headers = NewHeaders}, State)
    end,
    {reply, {ok, NewRequest#request.id}, State}.
```
- When calling `httpc:request` but doesn't specifiy a `profile` mean you will use `default profile` and by  default, each profile will have maximum 2 persistent connections per domain. If your application reach it, the `httpc_manager` doesn't start any more persistent connections and for each request, it just create then close the connection.
=> So more `profile` mean you will have more perstistent connetions and the application doesn't have to create-close connections consecutively so maybe it can fix the `socket_closed_remotely`

=> As I though, for simple we just need to increase the persistent connections option is okay.

**Comment by turtleDeng** [comment]
Thank you for your participation. The latest version already supports the retransmission mechanism.
