### ISSUE TITLE
auth.http.auth_req.params parameters can use json format data?

### ISSUE THREAD

**Issue by lhl5230** [emqx/emqx-auth-http#79]
Under the emq_auth_http.conf configuration file, can the parameters of auth.http.auth_req.params be in json format?
Like: auth.http.auth_req.params = {"clientid":%c,"username":%u,"password":%P}
I tried, but failed

**Comment by terry-xiaoyu** [comment]
No, I suggest you customize the code and put that Json structure into the http message body.
