### ISSUE TITLE
Is cache available for emqx-auth-http plugin? 

### ISSUE THREAD

**Issue by leoncool** [emqx/emqx-auth-http#83]
Dear there

Is cache available for emqx-auth-http plugin?  Similar to the Mosquitto MQTT HTTP auth, a parameter of caching time can be set so that same auth response will be provided for requests within the time period?

**Comment by Gilbert-Wong** [comment]
Hi, leoncool, sorry for respond so late. You can config acl cache in emqx.conf.

**Comment by honarkhah** [comment]
Where it is? could you give me documentation?

**Comment by terry-xiaoyu** [comment]
@honarkhah There's only a configuration for caching ACL results but no caching mechanism for auth request.

**Comment by honarkhah** [comment]
Is there any plan to cache auth requests? Or we should handle this issue?

**Comment by turtleDeng** [comment]
Sorry, the caching mechanism for auth requests will not be supported.

**Comment by turtleDeng** [comment]
Thank you for your participation, we will close this issue.
