### ISSUE TITLE
Authenticate on /mqtt/superuser and /mqtt/acl request?

### ISSUE THREAD

**Issue by seksity** [emqx/emqx-auth-http#85]
I using **emqx-auth-http** request to authenticate with API server. As API server should not use session and required to authenticate with username and password on each API request (Or, using JWT in short time period for security).

In document of **emqx-auth-http** using username/password on **/mqtt/auth** request only, while on **/mqtt/superuser** and **/mqtt/acl** not documentation about that.

So, I need you confirm that is no authenticate on that both request?, otherwise please you suggest to use authentication with EMQ too.

Thanks.

**Comment by Gilbert-Wong** [comment]
Yes, the document is not concise and easy to understand. In fact, this plugin is used to request auth info or acl info from user's http server, the url and parameters could be configured by yourself. We would add documents later.

**Comment by seksity** [comment]
Means both /mqtt/super user and /mqtt/acl already request username and password in url parameters to authenticate but it not yet shows in document ?

**Comment by Gilbert-Wong** [comment]
Yes, but you need to set the parameters in your http request. The /mqtt/super is a little different, using this plugin to request acl info will increase cpu usage and it would be a performance bottlenecks. Using superuser to author authentication will author just one time and later it would not execute check_acl action which would improve the performance.
