### ISSUE TITLE
No ACL request

### ISSUE THREAD

**Issue by armersong** [emqx/emqx-auth-http#89]
I setup http server and server can receives auth and super request, but there is no acl request. Is something wrong with the configuration?

thanks.

emqtt version: 2.3.11
emq_auth_http.conf:

auth.http.auth_req = http://127.0.0.1:8090/v1/mqtt/auth
auth.http.auth_req.method = post
auth.http.auth_req.params = clientid=%c,username=%u,password=%P,ipaddr=%a

auth.http.super_req = http://127.0.0.1:8090/v1/mqtt/superuser
auth.http.super_req.method = post
auth.http.super_req.params = clientid=%c,username=%u,ipaddr=%a

auth.http.acl_req = http://127.0.0.1:8090/v1/mqtt/acl
auth.http.acl_req.method = post
auth.http.acl_req.params = access=%A,username=%u,clientid=%c,ipaddr=%a,topic=%t

**Comment by terry-xiaoyu** [comment]
Your config looks good, try to publish an mqtt message to see if the ACL request is sent.

**Comment by armersong** [comment]
I did try to send sub and pub, but no request received.  How can i find out if the ACL request is sent?

**Comment by turtleDeng** [comment]
@armersong Superuser will skip the ACL, so please use the following configuration.
```
auth.http.auth_req = http://127.0.0.1:8090/v1/mqtt/auth
auth.http.auth_req.method = post
auth.http.auth_req.params = clientid=%c,username=%u,password=%P,ipaddr=%a

auth.http.acl_req = http://127.0.0.1:8090/v1/mqtt/acl
auth.http.acl_req.method = post
auth.http.acl_req.params = access=%A,username=%u,clientid=%c,ipaddr=%a,topic=%t
```

**Comment by armersong** [comment]
got it. thanks!

**Comment by TheBeachMaster** [comment]
Thanks @gilbertwong96  for this tip. Caused a lot of production headaches. It would be a great idea if the superuser issue was documented.
