### ISSUE TITLE
Adding interval between auth requests for same clientId

### ISSUE THREAD

**Issue by berk-can** [emqx/emqx-auth-http#93]
when mqtt-auth-http returns 4xx, clients try to reconnect every second which creates enormous traffic, is there any way to provide an interval in someway to be able to cache last unauthorized request for some interval so that it doesnt make http request for same clientId every time client tries to connect?

**Comment by Gilbert-Wong** [comment]
@berk-can , Thanks for you feedback. It is definitely a good feature. We would add this feature in our development plan.

**Comment by berk-can** [comment]
thank you for your interest, I would be happy to see that
