### ISSUE TITLE
Is topic available in auth request?

### ISSUE THREAD

**Issue by Clan-Utility** [emqx/emqx-auth-http#95]
According to [http://emqtt.com/docs/v2/guide.html#http](http://emqtt.com/docs/v2/guide.html#http), %t = topic can be used in auth_req. But on [https://github.com/emqx/emqx-auth-http/blob/master/README.md](https://github.com/emqx/emqx-auth-http/blob/master/README.md), %t is not available.

**Comment by svrooij** [comment]
The first link is about the `v2` docs, while the current version is `v3`, that might be an issue.

Why would you want to use the topic in the auth request?
In the auth request you probably don't have the topic, because with mqtt you first have to connect before you can subscribe to a topic.

**Comment by Clan-Utility** [comment]
In my case, one client always pub to one topic. So if %t is available for AUTH, I do not need to chain ACL.

There is no problem to do AUTH in connection stage and do ACL in pub/sub stage.

**Comment by turtleDeng** [comment]
In the MQTT protocol, authentication does not include a topic, so it is not supported when using the auth request.

**Comment by Clan-Utility** [comment]
I think this issue could be closed after the [doc](http://emqtt.com/docs/v3/guide.html#http) get updated

From
```
## Variables: %u = username, %c = clientid, %a = ipaddress, %P = password, %t = topic
```
to
```
## Variables: %u = username, %c = clientid, %a = ipaddress, %P = password
```

**Comment by HJianBo** [comment]
Yes! We have updated all of the Chinese and English document for EMQ X v3.1. And it will be released a few days later

**Comment by turtleDeng** [comment]
Thank you for your participation, we have said that the document is continuously updated.
