### ISSUE TITLE
i want pass http auth to the private ip network

### ISSUE THREAD

**Issue by 22factor** [emqx/emqx-auth-http#96]
i want no use http auth to the private ip network ( this private ip is administrator ip network.)
However, regular users should check the authentication. (regular users is public ip network)

Is there any way to set this up?

**Comment by turtleDeng** [comment]
@22factor 
It is recommended that you add a listening port to EMQX for administrator login, set to allow anonymous login to solve your problem.

**Comment by turtleDeng** [comment]
Thank you for your participation, I will close this issue.
